#!/bin/sh
#
# It removes files from previous versions not needed anymore
#
rm -f /usr/info/infview.inf
rm -f /usr/info/infview.info
rm -f /usr/local/info/infview.inf
rm -f /usr/local/info/infview.info


