#!/bin/sh
#
# It removes files from previous versions not needed anymore
#
rm -f @@pref@@/info/editor.inf
rm -f @@pref@@/info/infview.inf
rm -f @@pref@@/info/sdg.inf
rm -f @@pref@@/info/editor.info
rm -f @@pref@@/info/infview.info
rm -f @@pref@@/info/sdg.info
rm -f @@pref@@/info/editor.info.gz
rm -f @@pref@@/doc/setedit/*.txt


