#!/bin/sh
rm configure.cache
export CFLAGS='-O2 -Wall -Werror -gstabs+3 -pipe'
export CXXFLAGS='-O2 -Wall -Werror -gstabs+3 -pipe'
rm -f Makefile
perl config.pl --static --no-fhs --Xcppflags=-O3\ -fomit-frame-pointer\ -ffast-math
