#!/bin/sh
rm -f configure.cache
rm -f Makefile
perl config.pl --no-fhs --Xcppflags=-O3\ -fomit-frame-pointer\ -ffast-math --cflags=-O2\ -Wall\ -Werror\ -gstabs+3\ -pipe --cxxflags=-O2\ -Wall\ -Werror\ -gstabs+3\ -pipe
