__("Error")
__("Pocket Calculator")
__("Can't open file")
__("Comment inside section name")
__("Unterminated section name")
__("Empty section name")
__("Syntax error")
__("Missing open section {")
__("Missing close section }")
__("Missing equal sign")
__("Missing value after equal")
__("Unterminated string")
__("Non branch in base")
__("Trying to overwrite a value with a section")
__("Trying to overwrite a section with a value")
__("Windows not present")
__("Clipboard in use by other application")
__("Clipboard too big for the transfer buffer")
__("Not enough memory")
__("Windows reports error")
__("type not registered: %s\n")
__("Change Directory")
__("Directory ~n~ame")
__("Directory ~t~ree")
__("~O~K")
__("~C~hdir")
__("~R~evert")
__("Help")
__("Drives")
__("Invalid directory")
__("Colors")
__("~G~roup")
__("~I~tem")
__("~F~oreground")
__("~B~ackground")
__("Text ")
__("Color")
__("~T~ry")
__("Cancel")
__("Clipboard")
__("Untitled")
__("~F~iles")
__("~O~pen")
__("~A~dd")
__("~S~elect")
__("~R~eplace")
__("~C~lear")
__("Done")
__("~H~elp")
__("Invalid drive or directory")
__("Invalid file name.")
__("Jan")
__("Feb")
__("Mar")
__("Apr")
__("May")
__("Jun")
__("Jul")
__("Aug")
__("Sep")
__("Oct")
__("Nov")
__("Dec")
__("Invalid character in input")
__("<empty>")
__("Normal")
__("Highlight")
__("Underline")
__("Inverse")
__("Value not in the range %lu to %lu")
__("Value not in the range %li to %li")
__("Find")
__("~T~ext to find")
__("~C~ase sensitive")
__("~W~hole words only")
__("O~K~")
__("Replace")
__("~N~ew text")
__("~P~rompt on replace")
__("~R~eplace all")
__("~F~ile")
__("~N~ew")
__("~S~ave")
__("S~a~ve as...")
__("~C~hange dir...")
__("S~h~ell")
__("E~x~it")
__("~E~dit")
__("~U~ndo")
__("Cu~t~")
__("~C~opy")
__("~P~aste")
__("~S~how clipboard")
__("~S~earch")
__("~F~ind...")
__("~R~eplace...")
__("~S~earch again")
__("~W~indows")
__("~S~ize/move")
__("~Z~oom")
__("~T~ile")
__("C~a~scade")
__("~N~ext")
__("~P~revious")
__("~C~lose")
__("~F10~ Menu")
__("~F2~ Save")
__("~F3~ Open")
__("~Alt+F3~ Close")
__("~F5~ Zoom")
__("~F6~ Next")
__("Not enough memory for this operation.")
__("Error reading file %s.")
__("Error writing file %s.")
__("Error creating file %s.")
__("%s has been modified. Save?")
__("Save untitled file?")
__("Save file as")
__("~N~ame")
__("Search string not found.")
__("Replace this occurence?")
__("that's an interactive application, don't redirect stdin")
__("failed to get the name of the current terminal used for input")
__("failed to open the input terminal")
__("can't get input terminal attributes")
__("can't set input terminal attributes")
__("ioctl VT_SETMODE failed")
__(""
"that's an interactive application, don't redirect stdout. If you want to "
"collect information redirect stderr like this: program 2> file")
__("failed to get the name of the current terminal used for output")
__("failed to open the output terminal")
__("can't get output terminal information")
__("can't configure terminal mode")
__("Error! %s")
__("No available selection")
__("Unsupported data type")
__("No data")
__("X11 error")
__("Another application holds the clipboard")
__("Could not open '%s' for reading")
__("Save to file")
__("~Y~es")
__("~N~o")
__("Warning")
__("Information")
__("Confirm")
__("Don't warn you next time")
