// This is a fake file containing the strings that should be
// internationalized and are defined in Turbo Vision (outside
// setedit).

__("Error")
__("Pocket Calculator")
__("type not registered: %s\n")
__("Change Directory")
__("Directory ~n~ame")
__("Directory ~t~ree")
__("~O~K")
__("~C~hdir")
__("~R~evert")
__("Help")
__("Drives")
__("Invalid directory")
__("Colors")
__("~G~roup")
__("~I~tem")
__("~F~oreground")
__("~B~ackground")
__("Text ")
__("Color")
__("~T~ry")
__("Cancel")
__("Clipboard")
__("Untitled")
__("~F~iles")
__("Done")
__("~H~elp")
__("Invalid drive or directory")
__("Invalid file name.")
__("Jan")
__("Feb")
__("Mar")
__("Apr")
__("May")
__("Jun")
__("Jul")
__("Aug")
__("Sep")
__("Oct")
__("Nov")
__("Dec")
__("Invalid character in input")
__("<empty>")
__("Normal")
__("Highlight")
__("Underline")
__("Inverse")
__("~Alt-X~ Exit")
__("Value not in the range %lu to %lu")
__("Value not in the range %li to %li")
__("Type EXIT to return...")
__("Find")
__("~T~ext to find")
__("~C~ase sensitive")
__("~W~hole words only")
__("O~K~")
__("Replace")
__("~N~ew text")
__("~P~rompt on replace")
__("~R~eplace all")
__("~F~ile")
__("~O~pen")
__("~N~ew")
__("~S~ave")
__("S~a~ve as...")
__("~C~hange dir...")
__("~D~OS shell")
__("E~x~it")
__("~E~dit")
__("~U~ndo")
__("Cu~t~")
__("~C~opy")
__("~P~aste")
__("~S~how clipboard")
__("~C~lear")
__("~S~earch")
__("~F~ind...")
__("~R~eplace...")
__("~S~earch again")
__("~W~indows")
__("~S~ize/move")
__("~Z~oom")
__("~T~ile")
__("C~a~scade")
__("~N~ext")
__("~P~revious")
__("~C~lose")
__("~F2~ Save")
__("~F3~ Open")
__("~Alt+F3~ Close")
__("~F5~ Zoom")
__("~F6~ Next")
__("~F10~ Menu")
__("Not enough memory for this operation.")
__("Not enough memory for this operation")
__("Error reading file ")
__("Error writing file ")
__("Error creating file ")
__(" has been modified. Save?")
__("Save untitled file?")
__("Save file as")
__("~N~ame")
__("Search string not found.")
__("Replace this occurence?")
__("Could not open '%s' for reading")
__("Save to file")
__("~Y~es")
__("~N~o")
__("Warning")
__("Information")
__("Confirm")
__("Don't warn you next time")
